# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "7"
before_script:
  - npm install -g gulp gitbook-cli
script: gulp
cache:
  directories:
    - "node_modules"
# By default, the gh-pages branch is not built unless added to the whitelist.
branches:
  only:
    - master